Matrix Multiplication - without using numpy library

In [ ]:
import time
start=time.time()
a=[[1,2,3],[4,5,6],[7,8,9]]
b=[[0,6,1],[7,1,8],[10,12,13]]
result=[]
def matrixMultiplication():

  len_row=len(a)
  len_col=len(b[0])
  for i in range(len_row):
    new_matrix=[]

    for j in range(len_col):
      sum=0
      for k in range(len(b)):
        sum+=a[i][k]*b[k][j]
      new_matrix.append(sum)
    result.append(new_matrix)
    end=time.time()
  print("Multiplication of matrix A and B is : ",result)
  print("Time taken to run the code without using library : ",end-start)
matrixMultiplication()

Multiplication of matrix A and B is :  [[44, 44, 56], [95, 101, 122], [146, 158, 188]]
Time taken to run the code without using library :  0.00037741661071777344


Matrix Multiplication - Using numpy library

In [ ]:
import numpy as np
import time
start=time.time()
a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

b = [[0, 6, 1],
     [7, 1, 8],
     [10, 12, 13]]
end=time.time()
print("Time taken to run the code using library : ",end-start)
print(np.dot(a,b))


Time taken to run the code using library :  0.00011515617370605469
[[ 44  44  56]
 [ 95 101 122]
 [146 158 188]]
